name: 'telegram_etl'
version: '1.0.0'
config-version: 2

profile: 'telegram_profile'

model-paths: ["models"]
seed-paths:  ["seeds"]

# Models go into analytics schema by default
models:
  telegram_etl:
    +schema: analytics
